version: '3.4'

services:
  lionbackend:
    image: lionbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5001:5001
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
